org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

author=RogueLogix, UnnamedUser12
modid=phosphophyllite
mod_name=Phosphophyllite
mod_named=Phosphophyllite
description=Library mod for the BiggerSeries
license=LGPL v2.1
tag_lanzador=NeoForge
group=modernmods.phosphophylliterevived
mod_version=2.0.0
compatibility=[2.0.0,)

# Minecraft and NeoForge versions
mcversion=26.1.2
neoversion=26.1.2.107
loader_version=[4,)

# NeoForge Parchment


neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Dependencies
mekanism_version=1.21.1-10.7.19.85
